# Generated by Django 5.0.1 on 2024-04-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_predictionresult_chest_pain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='chest_pain_type',
            field=models.IntegerField(default=0),
        ),
    ]
