# Generated by Django 5.0.1 on 2024-04-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_predictionresult_chest_pain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='BP',
            field=models.IntegerField(default=0),
        ),
    ]
